### ISSUE TITLE
training with multiple gpus

### ISSUE THREAD

**Issue by YinqiCai** [duyhominhnguyen/LVM-Med#15]
Hi author, thanks for your excellent work! 
I have a problem with training with multiple gpus. In ``MedSAM_2d.py``， I find you write some codes to utilize gpus well, can I directly set nn.DataParallel and data.cuda() like:
```python
# set dataparallel
sam_model = torch.nn.DataParallel(sam_model, device_ids=[0,1,2,3])
image_encoder = torch.nn.DataParallel(sam_model.image_encoder, device_ids=[0,1,2,3])
prompt_encoder = torch.nn.DataParallel(sam_model.prompt_encoder, device_ids=[0,1,2,3])
mask_decoder = torch.nn.DataParallel(sam_model.mask_decoder, device_ids=[0,1,2,3])
# move data to cuda
images = images.cuda()
...
```

Thanks and regards.

**Comment by ngctnnnn** [comment]
Hi, 

To the best of my knowledge, by using `images.cuda()`, you only declare to use single gpu instead of multi-gpu. It might lead to the difference in gpu id between model and image, i.e., the image is in a different gpu from the current model. I think you could resolve this by applying single gpu to all SAM's components or using multi-gpu for the images.

Hope it might help.

**Comment by YinqiCai** [comment]
> Hi,
> 
> To the best of my knowledge, by using `images.cuda()`, you only declare to use single gpu instead of multi-gpu. It might lead to the difference in gpu id between model and image, i.e., the image is in a different gpu from the current model. I think you could resolve this by applying single gpu to all SAM's components or using multi-gpu for the images.
> 
> Hope it might help.

Thanks for your reply! I will try it, thanks!
